anaconda3 version 4.4.0 loaded.
“openmpi” version “1.8.4” loaded.
/N/u/shaoc/BigRed2/.conda_envs/gtpy3/lib/python3.6/site-packages/graph_tool/draw/cairo_draw.py:39: RuntimeWarning: Error importing cairo. Graph drawing will not work.
  warnings.warn(msg, RuntimeWarning)
/N/u/shaoc/BigRed2/.conda_envs/gtpy3/lib/python3.6/site-packages/graph_tool/draw/cairo_draw.py:39: RuntimeWarning: Error importing cairo. Graph drawing will not work.
  warnings.warn(msg, RuntimeWarning)
/N/u/shaoc/BigRed2/.conda_envs/gtpy3/lib/python3.6/site-packages/graph_tool/draw/cairo_draw.py:39: RuntimeWarning: Error importing cairo. Graph drawing will not work.
  warnings.warn(msg, RuntimeWarning)
/N/u/shaoc/BigRed2/.conda_envs/gtpy3/lib/python3.6/site-packages/graph_tool/all.py:40: RuntimeWarning: Error importing draw module, proceeding nevertheless: /usr/lib64/libxcb-xlib.so.0: undefined symbol: _xcb_unlock_io
  warnings.warn(msg, RuntimeWarning)
Traceback (most recent call last):
  File "pa_1g.py", line 7, in <module>
    n = int(argv[1])
NameError: name 'argv' is not defined
